name = "everyday_meals"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.
target = "javascript"
[dependencies]
gleam_stdlib = ">= 0.41.0 and < 2.0.0"
lustre = ">= 4.6.1 and < 5.0.0"
plinth = ">= 0.5.0 and < 1.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
# decode = ">= 0.4.1 and < 1.0.0"
# birl = ">= 1.7.1 and < 2.0.0"
gleam_json = "1.0.1"                        # needed by lustre for the time being
omnimessage_lustre = ">= 0.1.0 and < 1.0.0"
shared = { path = "../shared" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.0 and < 2.0.0"
lucide_lustre = ">= 2.0.0 and < 3.0.0"
