name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: "1.6.1"
          rebar3-version: "3"
      - name: Install dependencies
        working-directory: ./frontend
        run: gleam deps download
      - name: Install npm deps
        working-directory: ./frontend
        run: npm ci
      - name: Build app
        working-directory: ./frontend
        run: gleam run -m lustre/dev build app --minify
      - name: Copy output to dist
        run: |
          mkdir -p dist
          cp frontend/index.html dist/index.html
          cp -r frontend/priv dist/priv
      - name: Update path in index.html to use minified app
        run: sed -i 's|priv/static/everyday_meals.mjs|priv/static/everyday_meals.min.mjs|' dist/index.html
      - name: Debug
        run: git status
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name everyday-meals
