name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
      - name: Install dependencies
        working-directory: ./frontend
        run: gleam deps download
      - name: Run tests
        working-directory: ./frontend
        run: gleam test
      - name: Check formatting
        working-directory: ./frontend
        run: gleam format --check src test
